--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/15/2023 5:52:50 PM
-- Server version: 8.0.33
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE customize_job;

--
-- Drop table `tasks`
--
DROP TABLE IF EXISTS tasks;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE customize_job;

--
-- Create table `users`
--
CREATE TABLE users (
  ID int UNSIGNED NOT NULL AUTO_INCREMENT,
  code varchar(255) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tasks`
--
CREATE TABLE tasks (
  ID int NOT NULL AUTO_INCREMENT,
  TaskName varchar(255) DEFAULT NULL,
  Point int DEFAULT NULL,
  UserID int DEFAULT NULL,
  CompleteDate datetime DEFAULT NULL,
  TaskType int DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'B-0506', 'Đặng Quốc Thắng'),
(2, 'B-0506', 'Đặng Quốc Thắng'),
(3, 'B-0506', 'Đặng Quốc Thắng'),
(4, 'B-0506', 'Đặng Quốc Thắng'),
(5, 'B-0506', 'Đặng Quốc Thắng'),
(6, 'B-0506', 'Đặng Quốc Thắng');

-- 
-- Dumping data for table tasks
--
INSERT INTO tasks VALUES
(1, 'Thi công PBI', 10, 1, '2023-05-15 09:35:10', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;