--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/16/2023 4:15:19 PM
-- Server version: 8.0.33
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE customize_job;

--
-- Drop procedure `GetPointsByUserAndDateRange`
--
DROP PROCEDURE IF EXISTS GetPointsByUserAndDateRange;

--
-- Drop table `tasks`
--
DROP TABLE IF EXISTS tasks;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE customize_job;

--
-- Create table `users`
--
CREATE TABLE users (
  ID int UNSIGNED NOT NULL AUTO_INCREMENT,
  code varchar(255) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  avatar varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `tasks`
--
CREATE TABLE tasks (
  ID int NOT NULL AUTO_INCREMENT,
  TaskID varchar(255) DEFAULT NULL,
  TaskName varchar(255) DEFAULT NULL,
  Point int DEFAULT NULL,
  UserID int DEFAULT NULL,
  CompleteDate datetime DEFAULT NULL,
  TaskType int DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 21,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

DELIMITER $$

--
-- Create procedure `GetPointsByUserAndDateRange`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GetPointsByUserAndDateRange (IN fromDate datetime, IN toDate datetime)
BEGIN

  SET toDate = DATE_ADD(toDate, INTERVAL 1 DAY);

  SELECT
    t.UserID,
    u.name AS Name,
    SUM(t.Point) AS Point,
    u.avatar AS Avatar
  FROM tasks t
    INNER JOIN users u
      ON t.UserID = u.ID
  WHERE t.CompleteDate >= fromDate
  AND t.CompleteDate < toDate
  GROUP BY t.UserID;
END
$$

DELIMITER ;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'B06-0474', 'Nguyễn Thùy Lan', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=e9c14c9d-205d-42bf-9dbf-1db49cc027c9&isScale=true&width=192&height=192'),
(2, 'B-0531', 'Nguyễn Văn Hùng', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=3263d8d0-60c9-4abf-ad22-5dea9914d866&isScale=true&width=192&height=192'),
(3, 'B-0763', 'Vũ Minh Quang', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=c6176806-56b1-49cd-97e9-88ea2ed818c7&isScale=true&width=192&height=192'),
(4, 'B06-0490', 'Lã Thanh Nam', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=0fd27f5d-344a-4a09-ba6b-01b55776fbef&isScale=true&width=192&height=192'),
(5, 'B-0765', 'Trần Khánh Minh', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=f6bfb0d5-5817-414d-978f-8bb242a0be8d&isScale=true&width=192&height=192'),
(6, 'B-0983', 'Nguyễn Đình Phú', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=7d910492-f290-447f-bac8-d9e124717b68&isScale=true&width=192&height=192'),
(7, 'B-0731', 'Nguyễn Trung Kiên', 'https://amismisa.misacdn.net/APIS/PlatformAPI/api/Avatar/56c33c47-78ec-4b3a-92ba-9fdb7830a6d4/misa.jpg?&avatarID=a36ecba9-707b-4e26-a364-78ceac1d6c77&isScale=true&width=192&height=192');

-- 
-- Dumping data for table tasks
--
INSERT INTO tasks VALUES
(1, '337844', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 3:: Lỗi không lấy lại danh sách thành phẩm sau khi lấy lại dữ liệu ở bước 2', 1, 1, '2023-05-16 04:58:30', 1),
(2, '335733', 'Phân bổ chi phí sản xuất chung : Lỗi quay mãi khi chuyển loại phiếu phân bổ', 1, 1, '2023-05-16 04:58:30', 1),
(3, '337828', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Kiến nghị bổ sung tổng cộng cho cột Định mức, Tỷ lệ phân bổ', 1, 1, '2023-05-16 04:58:30', 1),
(4, '337715', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Lỗi không sửa được cột số lượng TP, Bán TP', 1, 1, '2023-05-16 04:58:30', 1),
(5, '337844', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 3:: Lỗi không lấy lại danh sách thành phẩm sau khi lấy lại dữ liệu ở bước 2', 1, 1, '2023-05-16 05:21:10', 1),
(6, '335733', 'Phân bổ chi phí sản xuất chung : Lỗi quay mãi khi chuyển loại phiếu phân bổ', 1, 1, '2023-05-16 05:21:10', 1),
(7, '337828', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Kiến nghị bổ sung tổng cộng cho cột Định mức, Tỷ lệ phân bổ', 1, 1, '2023-05-16 05:21:10', 1),
(8, '337715', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Lỗi không sửa được cột số lượng TP, Bán TP', 1, 1, '2023-05-16 05:21:10', 1),
(9, '337844', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 3:: Lỗi không lấy lại danh sách thành phẩm sau khi lấy lại dữ liệu ở bước 2', 1, 2, '2023-05-16 05:21:13', 1),
(10, '335733', 'Phân bổ chi phí sản xuất chung : Lỗi quay mãi khi chuyển loại phiếu phân bổ', 1, 2, '2023-05-16 05:21:13', 1),
(11, '337828', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Kiến nghị bổ sung tổng cộng cho cột Định mức, Tỷ lệ phân bổ', 1, 2, '2023-05-16 05:21:13', 1),
(12, '337715', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Lỗi không sửa được cột số lượng TP, Bán TP', 1, 2, '2023-05-16 05:21:13', 1),
(13, '337844', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 3:: Lỗi không lấy lại danh sách thành phẩm sau khi lấy lại dữ liệu ở bước 2', 1, 5, '2023-05-16 05:21:23', 1),
(14, '335733', 'Phân bổ chi phí sản xuất chung : Lỗi quay mãi khi chuyển loại phiếu phân bổ', 1, 5, '2023-05-16 05:21:23', 1),
(15, '337828', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Kiến nghị bổ sung tổng cộng cho cột Định mức, Tỷ lệ phân bổ', 1, 5, '2023-05-16 05:21:23', 1),
(16, '337715', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Lỗi không sửa được cột số lượng TP, Bán TP', 1, 5, '2023-05-16 05:21:23', 1),
(17, '337844', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 3:: Lỗi không lấy lại danh sách thành phẩm sau khi lấy lại dữ liệu ở bước 2', 1, 5, '2023-05-16 05:21:23', 1),
(18, '335733', 'Phân bổ chi phí sản xuất chung : Lỗi quay mãi khi chuyển loại phiếu phân bổ', 1, 5, '2023-05-16 05:21:23', 1),
(19, '337828', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Kiến nghị bổ sung tổng cộng cho cột Định mức, Tỷ lệ phân bổ', 1, 5, '2023-05-16 05:21:23', 1),
(20, '337715', 'Tính giá thành theo phương pháp phân bước liên tục - Bước 2: Lỗi không sửa được cột số lượng TP, Bán TP', 1, 5, '2023-05-16 05:21:23', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;